export const SLOT_STATUS = {
  AVAILABLE: "AVAILABLE",
  LOCKED: "LOCKED",
  BOOKED: "BOOKED",
  MAINTENANCE: "MAINTENANCE"
};

export const VENUE_STATUS = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  REJECTED: "REJECTED"
};

export const ROLE = {
  GUEST: "GUEST",
  CUSTOMER: "CUSTOMER",
  ADMIN_VENUE: "ADMIN_VENUE",
  COACH: "COACH",
  UMKM_SELLER: "UMKM_SELLER",
  SUPER_ADMIN: "SUPER_ADMIN"
};